### ISSUE TITLE
Windows: AttributeError: module 'os' has no attribute 'O_NOFOLLOW' in output.py (_save_output) — scan output never written

### ISSUE THREAD

**Issue by shivaprakash236** [opengrep/opengrep#794]
## Environment
- **OS**: Windows
- **opengrep version**: 1.27.1
- **Invocation**: opengrep.exe with `--sarif -o <output_file>`

## Description
After a scan completes successfully, opengrep crashes when attempting to write the output file. The binary fails with: AttributeError: module 'os' has no attribute 'O_NOFOLLOW'

`os.O_NOFOLLOW` is a POSIX-only flag (available on Linux/macOS) used to prevent symlink following when opening files. It does not exist on Windows, so `output.py` crashes at the point of writing results — meaning the scan runs to completion but **no output is ever produced**.

## Traceback
Traceback (most recent call last):
File "semgrep\commands\wrapper.py", line 41, in wrapper
File "semgrep\commands\scan.py", line 834, in scan
File "semgrep\output.py", line 454, in output
File "semgrep\output.py", line 515, in _save_output
AttributeError: module 'os' has no attribute 'O_NOFOLLOW'

## Root Cause
`output.py` line 515 uses `os.O_NOFOLLOW` unconditionally. This flag is not defined on Windows.

## Impact
- **Severity**: High — blocks all SARIF/JSON output on Windows regardless of scan success
- **Workaround**: None known; removing `-o <file>` and capturing stdout may be possible in some pipelines

**Comment by shivaprakash236** [comment]
This is a regression BUG caused by the https://github.com/opengrep/opengrep/pull/780 PR in OpenGrep v1.27.0, and it is specific to the Windows platform.

**Comment by dimitris-m** [comment]
> This is a regression BUG caused by the [#780](https://github.com/opengrep/opengrep/pull/780) PR in OpenGrep v1.27.0, and it is specific to the Windows platform.

Indeed, thanks for reporting.

**Comment by shivaprakash236** [comment]
Thank you @dimitris-m for quick fix.

**Comment by dimitris-m** [comment]
> Thank you @dimitris-m for quick fix.

Expect release today
