### ISSUE TITLE
Regression `unexpected keyword argument 'opengrep_ignore_pattern'

### ISSUE THREAD

**Issue by dragonfleas** [opengrep/opengrep#416]
**Describe the bug**

It appears to be that there's a regression in opengrep that reintroduced the bug reported in #241 and resolved in https://github.com/opengrep/opengrep/commit/ba4bbfbea5f83dab390ff092c19ef624c84dfc83

**To Reproduce**
Steps to reproduce the behavior.
If the issue is dependent on a specific rule and/or files, please paste the command line parameters and applicable file contents.

- Install opengrep v1.9.0
- Run the following:
  ```
  LC="$(locale -a|grep -ix 'c.utf-\?8' || echo C)"
  export LC_ALL="$LC"
  opengrep ci --config auto --sarif > opengrep.sarif
  ```

**Expected behavior**

It runs successfully.

**Screenshots**

<img width="1062" height="702" alt="Image" src="https://github.com/user-attachments/assets/33410bfc-074c-420e-8c3e-f18077360121" />

**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Opengrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
Are you running off docker, an official binary, a local build?

GitHub Actions (Virtual Machine, not inside docker)

**Use case**
What will fixing this bug enable for you?

Us to be able to security scan once more.

**Comment by dimitris-m** [comment]
Thanks for reporting this, fixed in https://github.com/opengrep/opengrep/pull/418.
